services:
  web:
    build: .
    depends_on:
      - db
    image: app-espaco-autoestima
    command: python app.py 
    volumes:
      - web_data:/controllers
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: E$p@c02024!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data:
  web_data: