services:
 web:
  build: .
  depends_on:
    - db
  image: app-espaco-autoestima
  command: python app.py 
  volumes:
    - web_data:/controllers
  ports:
    - "5000:5000"
 db:
    image: mysql:5.7
    environment:
      #MYSQL_HOST: 172.17.0.2
      #MYSQL_HOST: 172.17.0.3
      MYSQL_HOST: 172.17.0.1
      MYSQL_DATABASE: espacoautoestima
      MYSQL_ROOT_PASSWORD: E$p@c02024!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
volumes:
  db_data:
  web_data: