version: '3.9'
services:
 web:
  build: .
  command: python app.py 
  ports:
    - "5000:5000"
 db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: E$p@c02024!
      MYSQL_DATABASE: espacoautoestima
      MYSQL_USER: root
      MYSQL_PASSWORD: E$p@c02024!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"
volumes:
 db_data: