version: '3.10'
services:
 web:
  build: .
  working_dir: /data
  command: python clientes.py 
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5000:5000"
 db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: espacoautoestima
      MYSQL_HOST: 172.17.0.2
      MYSQL_USER: root
      MYSQL_PASSWORD: E$p@c02024!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"
volumes:
 db_data: